[package]
name = "joystiq"
edition = "2024.beta" 
license = "MIT"         
authors = ["Hercules (sirhercules27@yahoo.com)"]     

[dependencies]


[addresses]
joystiq = "0x7595ad0a79228628cf186c3ae70d0c94e78b8071a7dcaaab3e7104cd87b8af84"

[dev-dependencies]

[dev-addresses]