[package]
name = "joystiq"
edition = "2024.beta" 
license = "MIT"         
authors = ["Hercules (sirhercules27@yahoo.com)"]     

[dependencies]


[addresses]
joystiq = "0xeace579752cd466d91aa73a60829674829d3e329bde76625340528b3954b79ea"

[dev-dependencies]

[dev-addresses]